added -h flag

diff --git a/RSS b/RSS
--- a/RSS
+++ b/RSS
@@ -3,7 +3,7 @@
 # Written By Woland
 
 # Super basic RSS script
-# Add RSS link to FEED_URL
+# Add RSS link to FEED_URL or specify with -f 
 
 #Dependency:
 #          curl sed awk
@@ -11,11 +11,44 @@
 # https://github.com/wolandark
 # https://github.com/wolandark/BASH_Scripts_For_Everyone
 
-# URL of the RSS feed
+USAGE="Usage: $0 [-h] [-f FEED_URL]"
+
+usage() {
+  echo $USAGE
+  echo "  -h                display this help message"
+  echo "  -f FEED_URL       specify the URL of the RSS feed"
+}
+
 FEED_URL="http://rss.cnn.com/rss/cnn_topstories.rss"
 
-# Download the RSS feed
+while getopts ":hf:" opt; do
+  case ${opt} in
+    h )
+      usage
+      exit 0
+      ;;
+    f )
+      FEED_URL=$OPTARG
+      ;;
+    \? )
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      exit 1
+      ;;
+    : )
+      echo "Option -$OPTARG requires an argument." >&2
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$FEED_URL" ]; then
+  echo "Please provide a URL for the RSS feed."
+  usage
+  exit 1
+fi
+
 curl -s $FEED_URL > feed.xml
 
-# Extract the article titles
 sed -e 's/>/>\n/g' feed.xml | awk '/title/ , /\/title/' | grep -v 'title>' | sed -e 's/^.*\[//' -e 's/...$//'
diff --git a/aur b/aur
--- a/aur
+++ b/aur
@@ -10,11 +10,41 @@
 # https://github.com/wolandark
 # https://github.com/wolandark/BASH_Scripts_For_Everyone
 
-printf "Please type your search query\n"
-echo ''
+USAGE="Usage: $0 [-h] [-q query]"
 
-read query 
+usage() {
+  echo $USAGE
+  echo "  -h                display this help message"
+  echo "  -f FEED_URL       specify the search query"
+}
+# printf "Please type your search query\n"
+# echo ''
+
+# read query 
 # lynx https://archlinux.org/packages/?q=$query
+
+while getopts ":hq:" opt;do
+    case ${opt} in
+        h )
+            usage
+            exit 0
+            ;;
+        q )
+            query=$OPTARG
+            ;;
+        \? )
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
+        : )
+            echo "Option -OPTARG requires an argument." >&2
+            usage
+            exit 1
+            ;;
+    esac
+done
+
 
 w3m https://aur.archlinux.org/packages?O=0\&K=$query
 
diff --git a/ezdd b/ezdd
--- a/ezdd
+++ b/ezdd
@@ -7,13 +7,41 @@
 # https://github.com/wolandark
 # https://github.com/wolandark/BASH_Scripts_For_Everyone
 
-echo "Input .img or .iso file path" 
-read -re iso
-echo''
-lsblk 
-echo ''
-echo -e "Input USB device path to write to. All device paths must start with /dev\nexample: /dev/sdb"
-read -re dev
+while getopts ":hi:t:" opt; do
+  case $opt in
+    h)
+      echo "Usage: ./ezdd -i [path to .img or .iso file] -t [path to target USB device]"
+      exit 0
+      ;;
+    i)
+      iso=$OPTARG
+      ;;
+    t)
+      dev=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+if [[ -z $iso ]]; then
+  echo "Input .img or .iso file path:"
+  read -re iso
+fi
+
+if [[ -z $dev ]]; then
+  echo ""
+  lsblk
+  echo ""
+  echo -e "Input USB device path to write to. All device paths must start with /dev\nexample: /dev/sdb"
+  read -re dev
+fi
 
 sudo dd if=$iso of=$dev bs=4M status=progress
 
